#!/bin/sh

DESTDIR="${DESTDIR:-}"

mkdir -p "${DESTDIR}/sbin" "${DESTDIR}/usr/bin" "${DESTDIR}/etc"

cp init "${DESTDIR}/sbin/"
cp npli "${DESTDIR}/usr/bin/"
cp -rf npl-init "${DESTDIR}/etc/"
cp -rf acpi "${DESTDIR}/etc/"

ln -sf /etc/npl-init/npl-halt "${DESTDIR}/sbin/reboot"
ln -sf /etc/npl-init/npl-halt "${DESTDIR}/sbin/poweroff"
ln -sf /etc/npl-init/npl-halt "${DESTDIR}/sbin/halt"
ln -sf /etc/npl-init/npl-halt "${DESTDIR}/sbin/shutdown"

chmod +x "${DESTDIR}/sbin/init"
chmod +x "${DESTDIR}/usr/bin/npli"
chmod +x "${DESTDIR}/etc/npl-init/lib"
chmod +x "${DESTDIR}/etc/npl-init/npl-halt"
chmod +x "${DESTDIR}/etc/npl-init/sv/*"

chmod +x "${DESTDIR}/sbin/reboot"
chmod +x "${DESTDIR}/sbin/poweroff"
chmod +x "${DESTDIR}/sbin/shutdown"
chmod +x "${DESTDIR}/sbin/halt"

chmod +x "${DESTDIR}/etc/acpi/PWRB/00000080"
chmod +x "${DESTDIR}/etc/acpi/PWRF/00000080"
