#!/bin/sh

start() {
    while :; do
        openvt -w -f -c 2 -- sh -c 'exec getty 38400 tty2' >/dev/null 2>&1 || sleep 1
    done &
}

stop() {
    pkill -f "openvt.*-c 2" 2>/dev/null
    pkill -f "getty.*tty2" 2>/dev/null
}
