#!/bin/sh

start() {
    while true; do
        openvt -w -f -c 2 -- sh -c 'exec agetty -J tty2' || sleep 1
    done &
}

stop() {
    pkill -f 'openvt.*-c 2' 2>/dev/null
    pkill -f 'agetty.*tty2' 2>/dev/null
}
