#!/bin/sh

start() {
    while :; do
        openvt -w -f -c 5 -- sh -c 'exec getty 38400 tty5' >/dev/null 2>&1 || sleep 1
    done &
}

stop() {
    pkill -f "openvt.*-c 5" 2>/dev/null
    pkill -f "getty.*tty5" 2>/dev/null
}
