#!/bin/sh

start() {
    while :; do
        openvt -w -f -c 6 -- sh -c 'exec getty 38400 tty6' >/dev/null 2>&1 || sleep 1
    done &
}

stop() {
    pkill -f "openvt.*-c 6" 2>/dev/null
    pkill -f "getty.*tty6" 2>/dev/null
}
